### ISSUE TITLE
Might never finish collecting local candidates

### ISSUE THREAD

**Issue by vlad9486** [operutka/msf#1]
[Here](https://github.com/operutka/msf/blob/8def35597c6886054c916c4ebe204e9044a250a8/msf-ice/src/lib.rs#L314) is a local variable in method which called from `poll`.

If we have more then one channel the condition `resolved == self.channels.len()` might never met, because some channels might return pending. And will return `Ready` in further poll calls.

The fix may be to move `resolved` variable inside `AgentTask` structure.

**Comment by operutka** [comment]
I'm not sure if I follow here. The `process_local_candidates` method that you mentioned is supposed to close the `self.local_candidate_tx` channel once all channels are out of local candidates. I believe that this is precisely what it does.

The `resolved` variable will be equal to `self.channels.len()` when the `poll_next_local_candidate` method returns `Poll::Ready(None)` for all channels. The `poll_next_local_candidate` method follows an invariant common for fused streams, i.e. after it returns `Poll::Ready(None)`, it will always return `Poll::Ready(None)`. So the situation that the method would return `Poll::Ready(None)` in one call and `Poll::Pending` in another call cannot happen.

**Comment by vlad9486** [comment]
What about the situation that some of `channel` in `self.channels` return `Poll::Ready(Some(..))` and others return `Poll::Ready(None)`?

(Upd)
Aha, I see. In next invocations eventually, all of them return `Poll::Ready(None)`. And local counter is good.

**Comment by vlad9486** [comment]
Sorry, for botheried. I just have some problem with the library. I will debug further to find a true cause. Sometimes it just unable to send data, although gathering and signaling seems done.
